# Generated by Django 4.2.11 on 2024-04-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotels",
            name="availability",
            field=models.BooleanField(default=True),
        ),
    ]
